### ISSUE TITLE
error in miniflare: EvalError: Code generation from strings disallowed for this context

### ISSUE THREAD

**Issue by gobengo** [ipfs-elastic-provider/metrics-collector#17]
oops, ajv creates a function from a string, which is disabled in miniflare and on cloudflare workers.

We can compile the schema validators at built-time instead of runtime:
https://github.com/ajv-validator/ajv/blob/master/docs/standalone.md#two-step-process

```
Error compiling schema, function code: const schema2 = scope.schema[2];const schema1 = scope.schema[1];return function validate1(data, {instancePath="", parentData, parentDataProperty, rootData=data}={}){let vErrors = null;let errors = 0;const _errs1 = errors;if(!(((typeof data == "number") && (!(data % 1) && !isNaN(data))) && (isFinite(data)))){validate1.errors = [{instancePath,schemaPath:"#/definitions/nonNegativeInteger/type",keyword:"type",params:{type: "integer"},message:"must be integer"}];return false;}if(errors === _errs1){if((typeof data == "number") && (isFinite(data))){if(data < 0 || isNaN(data)){validate1.errors = [{instancePath,schemaPath:"#/definitions/nonNegativeInteger/minimum",keyword:"minimum",params:{comparison: ">=", limit: 0},message:"must be >= 0"}];return false;}}}validate1.errors = vErrors;return errors === 0;}
[mf:err] POST /events: EvalError: Code generation from strings disallowed for this context
    at new Function (<anonymous>)
    at Ajv2.compileSchema (/private/Users/bengo/protocol.ai/metrics-collector/node_modules/ajv/lib/compile/index.ts:171:26)
    at Ajv2.inlineOrCompile (/private/Users/bengo/protocol.ai/metrics-collector/node_modules/ajv/lib/compile/index.ts:228:45)
    at Ajv2.resolveRef (/private/Users/bengo/protocol.ai/metrics-collector/node_modules/ajv/lib/compile/index.ts:223:44)
    at Object.code (/private/Users/bengo/protocol.ai/metrics-collector/node_modules/ajv/lib/vocabularies/core/ref.ts:18:33)
    at keywordCode (/private/Users/bengo/protocol.ai/metrics-collector/node_modules/ajv/lib/compile/validate/index.ts:523:9)
    at /private/Users/bengo/protocol.ai/metrics-collector/node_modules/ajv/lib/compile/validate/index.ts:228:21
    at CodeGen.code (/private/Users/bengo/protocol.ai/metrics-collector/node_modules/ajv/lib/compile/codegen/index.ts:525:33)
    at CodeGen.block (/private/Users/bengo/protocol.ai/metrics-collector/node_modules/ajv/lib/compile/codegen/index.ts:680:20)
    at schemaKeywords (/private/Users/bengo/protocol.ai/metrics-collector/node_modules/ajv/lib/compile/validate/index.ts:228:9)
POST /events 500 Internal Server Error (178.18ms)
```

**Comment by gobengo** [comment]
@alanshaw saves the day with suggestion of https://www.npmjs.com/package/@cfworker/json-schema
